language: python
dist: bionic 
sudo: false
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
python:
  - "3.7"
  - "3.8"
script:
  - DEBUG=cypress:server:util:process_profiler make all
