# Generated by Django 2.2.6 on 2020-03-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseaffils', '0005_auto_20200317_1358'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('base_map', models.CharField(choices=[('streets-v11', 'Street'), ('outdoors-v11', 'Outdoors'), ('light-v10', 'Light'), ('dark-v10', 'Dark'), ('satellite-v9', 'Satellite'), ('satellite-streets-v11', 'Street - Satellite'), ('navigation-preview-day-v4', 'Navigation - Day'), ('navigation-preview-night-v4', 'Navigation - Night'), ('navigation-guidance-day-v4', 'Navigation/Guidance - Day'), ('navigation-guidance-night-v4', 'Navigation/Guidance - Night')], default='dark-v10', max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseaffils.Course')),
            ],
        ),
    ]
