# Generated by Django 2.2.6 on 2020-05-01 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20200501_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responseowner',
            unique_together={('owner', 'assignment')},
        ),
    ]
