# Generated by Django 2.2.14 on 2020-07-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20200501_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Activity'
        ),
        migrations.RenameField(
            model_name='response',
            old_name='assignment',
            new_name='activity'
        ),
        migrations.RenameField(
            model_name='responseowner',
            old_name='assignment',
            new_name='activity'
        ),
        migrations.AlterUniqueTogether(
            name='responseowner',
            unique_together={('owner', 'activity')},
        ),
    ]
