# Generated by Django 2.2.15 on 2020-08-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200715_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='main.Project'),
        ),
    ]
