# Generated by Django 2.2.15 on 2020-08-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200812_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='base_map',
            field=models.CharField(choices=[('streets-v11', 'Street'), ('outdoors-v11', 'Outdoors'), ('light-v10', 'Light'), ('dark-v10', 'Dark'), ('satellite-v9', 'Satellite'), ('satellite-streets-v11', 'Street - Satellite'), ('navigation-preview-day-v4', 'Navigation - Day'), ('navigation-preview-night-v4', 'Navigation - Night'), ('navigation-guidance-day-v4', 'Navigation/Guidance - Day'), ('navigation-guidance-night-v4', 'Navigation/Guidance - Night')], default='light-v10', max_length=64),
        ),
    ]
