# Generated by Django 2.2.17 on 2020-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200910_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='reflection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=12),
        ),
    ]
