# Generated by Django 2.2.17 on 2020-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201210_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media',
            field=models.ManyToManyField(blank=True, to='main.MediaObject'),
        ),
    ]
