# Generated by Django 2.2.17 on 2021-01-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210120_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Layer'),
        ),
    ]
