# Generated by Django 2.2.18 on 2021-02-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210129_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='body',
        ),
    ]
