# Generated by Django 2.2.18 on 2021-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210202_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
