# Generated by Django 2.2.19 on 2021-02-24 22:05

from django.db import migrations


def forwards(apps, schema_editor):
    Project = apps.get_model('main', 'Project')
    for p in Project.objects.all():
        p.base_map = 'mapbox://styles/mapbox/' + p.base_map
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rasterlayer'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
