# Generated by Django 2.2.19 on 2021-02-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210224_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='base_map',
            field=models.CharField(choices=[('mapbox://styles/mapbox/streets-v11', 'Street'), ('mapbox://styles/mapbox/outdoors-v11', 'Outdoors'), ('mapbox://styles/mapbox/light-v10', 'Light'), ('mapbox://styles/mapbox/dark-v10', 'Dark'), ('mapbox://styles/mapbox/satellite-v9', 'Satellite'), ('mapbox://styles/mapbox/satellite-streets-v11', 'Street - Satellite'), ('mapbox://styles/mapbox/navigation-preview-day-v4', 'Navigation - Day'), ('mapbox://styles/mapbox/navigation-preview-night-v4', 'Navigation - Night'), ('mapbox://styles/mapbox/navigation-guidance-day-v4', 'Navigation/Guidance - Day'), ('mapbox://styles/mapbox/navigation-guidance-night-v4', 'Navigation/Guidance - Night')], default='mapbox://styles/mapbox/light-v10', max_length=64),
        ),
    ]
