# Generated by Django 2.2.19 on 2021-03-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210224_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='layer',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rasterlayer',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
