# Generated by Django 3.2.16 on 2022-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210406_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='alt',
            field=models.TextField(blank=True),
        ),
    ]
