# Generated by Django 3.2.16 on 2022-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_mediaobject_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='color',
            field=models.CharField(default='amber', max_length=256),
        ),
    ]
