version: 2
jobs:
  test:
    docker:
    - image: cypress/base:ubuntu18-node12.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: apt-get install python3-venv -y
      - run: 
          name: Test
          command: make all
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - ~/.npm
          - ~/.cache
workflows:
  build:
    jobs:
    - test
  version: 2
