name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        node-version: [14.x]
    services:
      postgres:
        image: postgis/postgis:13-master
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y libgdal-dev
      - name: Build with Makefile
        run: make travis
